
# SEO settings
title: "Utkarsh"
title2: " Bodake" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: https://utkarshdbodake.github.io # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/utkarshdbodake.github.io
disqus_shortname: "utkarshdbodake"
twitter_username: "utkarshdbodake"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Utkarsh Bodake"
  job      : "Software Engineer"
  company  : "Crowdfire"
  bio      : "Below are some of my leanings in the software world."
  thumb    : /images/author.jpg
  email    : bodakeutkarsh@gmail.com
  url      : http://utkarshdbodake.github.io
  github   : http://github.com/utkarshdbodake
  twitter  : http://twitter.com/utkarshdbodake
  facebook : https://www.facebook.com/utkarshdbodake
  linkedin : https://www.linkedin.com/in/utkarshb

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@utkarshdbodake"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
#  - slug : blog
#    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
